trigger:
- none

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: AzurePowerShell@5
  inputs:
    azureSubscription: 'ARMStorageAccountPipeline'
    ScriptType: 'FilePath'
    ScriptPath: 'create_storage_account/Deploy-AzTemplate.ps1'
    ScriptArguments: -Location 'centralindia' -ResourceGroupName 'ResourceDeployment' -TemplateFile create_storage_account/Deploy-AzTemplate.ps1
    azurePowerShellVersion: 'LatestVersion'
